version: '3'
services:
  app:
    build: .
    command: "ruby ui.rb"
    volumes:
      - .:/hsm
    ports:
      - "4567:4567"
    environment:
      - github_token=7036a2c8017f1075fa6d9cf411e56aef5f578188
